# Generated by Django 5.1.2 on 2024-10-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabom", "0003_article_created_at_article_update_at_like_created_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(fields=("user", "article"), name="unique_user_article"),
        ),
    ]
